### ISSUE TITLE
Add github action for upload to pypi

### ISSUE THREAD

**Issue by Drulex** [neuropoly/changelog#14]

**Comment by Drulex** [comment]
@jcohenadad Could you add the `TWINE_USERNAME` and `TWINE_PASSWORD` to the repo's secrets section?

**Comment by jcohenadad** [comment]
@Drulex i've done it in the past and then forgot-- quick google sent me [there](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets) for setting up the values, but my question is: how do i get the values?

**Comment by Drulex** [comment]
The owner/creator of the `pypi` account should have them. Maybe copy them from the `ivadomed` secrets? Whoever set them up there should have them.

**Comment by jcohenadad** [comment]
OK, I remember what i did now. I've created a `PYPI_PASSWORD` at the organizational level (neuropoly/), which is valid for all repos inside it. So you should be able to use that.

p.s. i did document it [here](https://www.neuro.polymtl.ca/tips_and_tricks/python?s[]=pypi#packaging_your_code) (and then forgot there was a documentation about it...)

**Comment by Drulex** [comment]
Hurray first release https://pypi.org/project/changelog-neuropoly/1.0.0/
