### ISSUE TITLE
Specify milestone via optional argument

### ISSUE THREAD

**Issue by Drulex** [neuropoly/changelog#15]
It would be useful in case:
- multiple parallel milestones exist (internal milestones vs public milestones)
- need to regenerate changelog for a previous milestone
- flexibility in general

If no milestone is provided fetch the latest (no behavior change).

**Comment by joshuacwnewton** [comment]
I'm interested in taking this on, because it would make it a lot easier to work with the milestone name in GitHub Actions. See: https://github.com/neuropoly/spinalcordtoolbox/pull/3264#discussion_r587863138

**Comment by Drulex** [comment]
Absolutely go ahead!
