### ISSUE TITLE
Suggestion: directly prepend to existing CHANGES.md file

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/changelog#3]
Instead of manually-copying the content (prone to error, takes time), we could prepend the output to the existing CHANGES.* file (if it exists). 

Pointing to the file (if it has a different name) could be another argument.

**Comment by Drulex** [comment]
Proposing:
- Add `--update` optional argument (bool) which would update the changelog file directly.
- Add `--name` optional argument (`str` with default value of `CHANGES.md`) that is mutually inclusive to `--update` flag and serves to point to the changelog file.

When `--update` is used, the changelog file would be prepended directly.
