### ISSUE TITLE
Allow to use no label

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/changelog#4]
Currently, when using changelog function, labels need to be present on the PR. By default, those labels are expected: https://github.com/neuropoly/changelog/blob/master/changelog.py#L235.

However, it would be nice to be able to generate a changelog without labels for repos where labels are less relevant, e.g. https://github.com/spine-generic/data-multi-subject.

**Comment by joshuacwnewton** [comment]
I notice that we also rely on open milestones for generating our changelog. This would be another barrier for the `data-multi-subject` repo.

**Comment by jcohenadad** [comment]
> I notice that we also rely on open milestones for generating our changelog. This would be another barrier for the data-multi-subject repo.

excellent point! however, i am wondering how we should include PRs in the changelog without manually selecting milestones. Are you thinking of including all PRs which were merged after the date of the latest release?

**Comment by joshuacwnewton** [comment]
> however, i am wondering how we should include PRs in the changelog without manually selecting milestones. Are you thinking of including all PRs which were merged after the date of the latest release?

Alternatively, for now we could leave the milestone behavior as-is, but just start using milestones in `data-multi-subject` like the other projects. e.g. adding a `r20200806` milestone.

**Comment by joshuacwnewton** [comment]
I don't currently have permissions for `spine-generic` I don't think but otherwise I'd be happy to do some tagging. :)

**Comment by joshuacwnewton** [comment]
Thanks, @jcohenadad!

Alright, I've got a working solution. I think I'm missing permissions for this `changelog` repo as well, though, so I can't yet open a PR. :(
